[bumpversion]
commit = True
tag = True
current_version = 0.1.0
parse = (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(-(?P<stage>[^.]*))?
serialize = 
	{major}.{minor}.{patch}-{stage}
	{major}.{minor}.{patch}


[bumpversion:part:stage]
optional_value = stable
first_value = stable
values = 
	alpha
	beta
	stable